# Generated by Django 5.0.6 on 2024-06-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='is_public',
            new_name='public',
        ),
    ]
