# Generated by Django 5.0.6 on 2024-05-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
